/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "bitacora.h"
#include <stdio.h>
#include <stdlib.h>
//Recibe argumentos que son proporcionados por el Main
void bitacora_prog_1(char *host, char* opt, char *name)
{
    CLIENT *clnt;	//Se crea el cliente
	char * *result_1; //Resultado al hacer add
	char * add_1_arg; //Opción add
	char * *result_2; //Resultado al hacer search
	char * search_1_arg; //Opción search

#ifndef	DEBUG
	clnt = clnt_create (host, BITACORA_PROG, BITACORA_VERS, "udp");
	if (clnt == NULL) {	//Si es que el cliente no haya sido creado
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	if(strcmp(opt, "add")==0){//Opción que es lo mismo que "add"
		add_1_arg = name; //Se añade el nombre de la persona
		result_1 = add_1(&add_1_arg, clnt);
		if (result_1 == (char **) NULL) {
			//clnt_perror (clnt, "call failed");
		} else {
			printf("Server response: %s", *result_1); //Se imprime con éxito el resultado
		}
	}
	
	if(strcmp(opt, "search")==0){//Opción que es lo mismo que "search"
		search_1_arg = name;
		result_2 = search_1(&search_1_arg, clnt); //Se realiza la búsqueda de la persona
		if (result_2 == (char **) NULL) {
			//clnt_perror (clnt, "call failed");
		} else {
			printf("Server response: %s \n", *result_2); //Se imprimen los resultados
		}
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt); //Se destruye el cliente
#endif	 /* DEBUG */
}

int
main(int argc, char *argv[]) {
        char *host;
        char *name;
        char* opt;
        int id;
        if (argc != 4) {
            printf ("usage: %s host opt name\n", argv[0]);
            exit(1);
        }
        host = argv[1]; // Host.
        opt  = argv[2]; //Option.
        name = argv[3]; 

        if (strcmp(opt, "add")!=0 && strcmp(opt, "search")!=0) {
            fprintf(stderr, "invalid value: %s\n", argv[2]);
            exit(1);
        }

        bitacora_prog_1(host, opt, name);
}
